server:
  port: 8083
  servlet:
    context-path: /portalapps-services

spring:
  #Local
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
  hibernate:
    ddl-auto: validate

  datasource:
    url: jdbc:as400://caetano2.sc.pt
    username: JAVAUSER
    password: JAVAUSER
    driver-class-name: com.ibm.as400.access.AS400JDBCDriver

  #swagger
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  #request size
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

springdoc:
  swagger-ui:
    enabled: true
  show-actuator: true
  display-request-duration: true
  filter: true

# loggin config file by profile
log4j:
  configuration:
    path: log4j-local.properties

#Ficheiro de configuracao da SC
sc:
  config:
    file: ""


#customom properties ex local url
app:
  baseUrl: /portalapps


