server:
  port: 8083
  servlet:
    context-path: /portalapps-services

spring:
  #Local
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
  hibernate:
    ddl-auto: validate
    #se agregan las mismas conexiones a base que usa TVCMANAGER, hasta que nos entreguen la credenciales para este proyecto
  datasource:
    url: jdbc:db2://scdbesrva.sc.pt:50000/TOYXTAPS
    username: db2inst1
    password: db2admin
    driver-class-name: com.ibm.db2.jcc.DB2Driver

  #swagger
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  #request size
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

springdoc:
  swagger-ui:
    enabled: true
  show-actuator: true
  display-request-duration: true
  filter: true

# loggin config file by profile
log4j:
  configuration:
    path: log4j-local.properties

#Ficheiro de configuracao da SC
sc:
  config:
    file: ""


#customom properties ex local url
app:
  baseUrl: /portalapps


